"""add organization status column

Revision ID: 006068cf04a4
Revises: 17b509a55cc0
Create Date: 2026-03-25 16:47:19.470381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '006068cf04a4'
down_revision: Union[str, None] = '17b509a55cc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('organization_id', sa.NUMERIC(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('stripe_invoice_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('receipt_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
