"""add is_primary_admin to memberships

Revision ID: 17b509a55cc0
Revises: 
Create Date: 2026-03-24 09:36:40.760714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '17b509a55cc0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memberships')
    op.drop_table('subscriptions')
    op.drop_table('gifts_passions')
    op.drop_table('roles')
    op.drop_table('organizations')
    op.drop_table('questions')
    op.drop_table('types')
    op.drop_table('users')
    op.drop_table('question_types')
    op.drop_table('answers')
    op.drop_table('password_reset_tokens')
    op.drop_table('assessments')
    op.drop_table('audit_log')
    op.drop_table('assessment_results')
    op.drop_table('refresh_tokens')
    op.drop_table('invitations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('sign_up_key', sa.VARCHAR(length=255), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('organization_id', sa.NUMERIC(), nullable=True),
    sa.Column('created_by', sa.NUMERIC(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('accepted_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sign_up_key')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('user_id', sa.NUMERIC(), nullable=False),
    sa.Column('token', sa.TEXT(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('revoked', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('assessment_results',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('assessment_id', sa.NUMERIC(), nullable=False),
    sa.Column('user_id', sa.NUMERIC(), nullable=True),
    sa.Column('gift_1_id', sa.NUMERIC(), nullable=True),
    sa.Column('spiritual_gift_1_score', sa.SMALLINT(), nullable=True),
    sa.Column('gift_2_id', sa.NUMERIC(), nullable=True),
    sa.Column('spiritual_gift_2_score', sa.SMALLINT(), nullable=True),
    sa.Column('gift_3_id', sa.NUMERIC(), nullable=True),
    sa.Column('spiritual_gift_3_score', sa.SMALLINT(), nullable=True),
    sa.Column('gift_4_id', sa.NUMERIC(), nullable=True),
    sa.Column('spiritual_gift_4_score', sa.SMALLINT(), nullable=True),
    sa.Column('passion_1_id', sa.NUMERIC(), nullable=True),
    sa.Column('passion_1_score', sa.SMALLINT(), nullable=True),
    sa.Column('passion_2_id', sa.NUMERIC(), nullable=True),
    sa.Column('passion_2_score', sa.SMALLINT(), nullable=True),
    sa.Column('passion_3_id', sa.NUMERIC(), nullable=True),
    sa.Column('passion_3_score', sa.SMALLINT(), nullable=True),
    sa.Column('people', sa.TEXT(), nullable=True),
    sa.Column('cause', sa.TEXT(), nullable=True),
    sa.Column('abilities', sa.TEXT(), nullable=True),
    sa.Column('story_gift_answer', sa.TEXT(), nullable=True),
    sa.Column('story_ability_answer', sa.TEXT(), nullable=True),
    sa.Column('story_passion_answer', sa.TEXT(), nullable=True),
    sa.Column('story_influencing_answer', sa.TEXT(), nullable=True),
    sa.Column('story_onechange_answer', sa.TEXT(), nullable=True),
    sa.Column('story_closestpeople_answer', sa.TEXT(), nullable=True),
    sa.Column('story_oneregret_answer', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['gift_1_id'], ['gifts_passions.id'], ),
    sa.ForeignKeyConstraint(['gift_2_id'], ['gifts_passions.id'], ),
    sa.ForeignKeyConstraint(['gift_3_id'], ['gifts_passions.id'], ),
    sa.ForeignKeyConstraint(['gift_4_id'], ['gifts_passions.id'], ),
    sa.ForeignKeyConstraint(['passion_1_id'], ['gifts_passions.id'], ),
    sa.ForeignKeyConstraint(['passion_2_id'], ['gifts_passions.id'], ),
    sa.ForeignKeyConstraint(['passion_3_id'], ['gifts_passions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('user_id', sa.NUMERIC(), nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), nullable=False),
    sa.Column('target_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('target_id', sa.NUMERIC(), nullable=True),
    sa.Column('details', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessments',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('user_id', sa.NUMERIC(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('user_id', sa.NUMERIC(), nullable=False),
    sa.Column('token', sa.TEXT(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('used', sa.VARCHAR(length=1), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('answers',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('assessment_id', sa.NUMERIC(), nullable=False),
    sa.Column('question_id', sa.NUMERIC(), nullable=True),
    sa.Column('user_id', sa.NUMERIC(), nullable=False),
    sa.Column('multiple_choice_answer', sa.VARCHAR(length=255), nullable=True),
    sa.Column('numeric_value', sa.SMALLINT(), nullable=True),
    sa.Column('text_value', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_types',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('users',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('password_hash', sa.TEXT(), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=255), nullable=True),
    sa.Column('city', sa.VARCHAR(length=255), nullable=True),
    sa.Column('state', sa.VARCHAR(length=255), nullable=True),
    sa.Column('country', sa.VARCHAR(length=255), nullable=True),
    sa.Column('locale', sa.VARCHAR(length=10), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('stripe_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('types',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('order', sa.SMALLINT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('question', sa.TEXT(), nullable=False),
    sa.Column('question_es', sa.TEXT(), nullable=True),
    sa.Column('order', sa.INTEGER(), nullable=False),
    sa.Column('passion_type', sa.VARCHAR(length=255), nullable=True),
    sa.Column('passion_type_es', sa.VARCHAR(length=255), nullable=True),
    sa.Column('default_text', sa.TEXT(), nullable=True),
    sa.Column('default_text_es', sa.TEXT(), nullable=True),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.Column('summary_es', sa.TEXT(), nullable=True),
    sa.Column('type_id', sa.NUMERIC(), nullable=False),
    sa.Column('question_type_id', sa.NUMERIC(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['question_type_id'], ['question_types.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('city', sa.VARCHAR(length=255), nullable=True),
    sa.Column('state', sa.VARCHAR(length=255), nullable=True),
    sa.Column('country', sa.VARCHAR(length=255), nullable=True),
    sa.Column('key', sa.VARCHAR(length=255), nullable=False),
    sa.Column('package', sa.VARCHAR(length=255), nullable=True),
    sa.Column('stripe_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('card_brand', sa.VARCHAR(length=255), nullable=True),
    sa.Column('card_last_four', sa.VARCHAR(length=4), nullable=True),
    sa.Column('trial_ends_at', sa.DATETIME(), nullable=True),
    sa.Column('preferred_instrument', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('roles',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('gifts_passions',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('short_code', sa.VARCHAR(length=5), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('questions', sa.TEXT(), nullable=False),
    sa.Column('type_id', sa.NUMERIC(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_code')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('user_id', sa.NUMERIC(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('stripe_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('stripe_status', sa.VARCHAR(length=255), nullable=False),
    sa.Column('stripe_plan', sa.VARCHAR(length=255), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('trial_ends_at', sa.DATETIME(), nullable=True),
    sa.Column('ends_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memberships',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('user_id', sa.NUMERIC(), nullable=False),
    sa.Column('organization_id', sa.NUMERIC(), nullable=True),
    sa.Column('role_id', sa.NUMERIC(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
