"""add myimpact support

Revision ID: a9872764336e
Revises: 006068cf04a4
Create Date: 2026-03-25 20:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql, sqlite
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = 'a9872764336e'
down_revision: Union[str, None] = '006068cf04a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def column_exists(table_name, column_name):
    """Check if a column exists in the table"""
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def table_exists(table_name):
    """Check if a table exists"""
    conn = op.get_bind()
    inspector = inspect(conn)
    return table_name in inspector.get_table_names()


def index_exists(table_name, index_name):
    """Check if an index exists"""
    conn = op.get_bind()
    inspector = inspect(conn)
    indexes = [idx['name'] for idx in inspector.get_indexes(table_name)]
    return index_name in indexes


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Add instrument_type column to assessments table (if not exists)
    if not column_exists('assessments', 'instrument_type'):
        op.add_column('assessments', sa.Column('instrument_type', sa.String(length=20), nullable=False, server_default='gps'))
    
    # 2. Add index for efficient filtering (if not exists)
    if not index_exists('assessments', 'ix_assessments_instrument_type'):
        op.create_index('ix_assessments_instrument_type', 'assessments', ['instrument_type'])
    
    # 3. Add instrument_type and section columns to questions table (if not exists)
    if not column_exists('questions', 'instrument_type'):
        op.add_column('questions', sa.Column('instrument_type', sa.String(length=20), nullable=False, server_default='gps'))
    if not column_exists('questions', 'section'):
        op.add_column('questions', sa.Column('section', sa.String(length=50), nullable=True))
    
    # 4. Add index for efficient filtering (if not exists)
    if not index_exists('questions', 'ix_questions_instrument_type'):
        op.create_index('ix_questions_instrument_type', 'questions', ['instrument_type'])
    
    # 5. Create myimpact_results table (if not exists)
    if not table_exists('myimpact_results'):
        op.create_table('myimpact_results',
            sa.Column('id', sa.String(length=36), nullable=False),
            sa.Column('assessment_id', sa.String(length=36), nullable=False),
            sa.Column('user_id', sa.String(length=36), nullable=True),
            
            # Character scores (9 questions)
            sa.Column('c1_loving', sa.SMALLINT(), nullable=True),
            sa.Column('c2_joyful', sa.SMALLINT(), nullable=True),
            sa.Column('c3_peaceful', sa.SMALLINT(), nullable=True),
            sa.Column('c4_patient', sa.SMALLINT(), nullable=True),
            sa.Column('c5_kind', sa.SMALLINT(), nullable=True),
            sa.Column('c6_good', sa.SMALLINT(), nullable=True),
            sa.Column('c7_faithful', sa.SMALLINT(), nullable=True),
            sa.Column('c8_gentle', sa.SMALLINT(), nullable=True),
            sa.Column('c9_self_controlled', sa.SMALLINT(), nullable=True),
            sa.Column('character_score', sa.Float(), nullable=True),
            
            # Calling scores (8 questions)
            sa.Column('cl1_know_gifts', sa.SMALLINT(), nullable=True),
            sa.Column('cl2_know_people', sa.SMALLINT(), nullable=True),
            sa.Column('cl3_using_gifts', sa.SMALLINT(), nullable=True),
            sa.Column('cl4_see_impact', sa.SMALLINT(), nullable=True),
            sa.Column('cl5_experience_joy', sa.SMALLINT(), nullable=True),
            sa.Column('cl6_pray_regularly', sa.SMALLINT(), nullable=True),
            sa.Column('cl7_see_movement', sa.SMALLINT(), nullable=True),
            sa.Column('cl8_receive_support', sa.SMALLINT(), nullable=True),
            sa.Column('calling_score', sa.Float(), nullable=True),
            
            # Final MyImpact Score
            sa.Column('myimpact_score', sa.Float(), nullable=True),
            
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            
            sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        
        # 6. Create index on myimpact_results
        op.create_index('ix_myimpact_results_assessment_id', 'myimpact_results', ['assessment_id'])
        op.create_index('ix_myimpact_results_user_id', 'myimpact_results', ['user_id'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Drop myimpact_results table (if exists)
    if table_exists('myimpact_results'):
        if index_exists('myimpact_results', 'ix_myimpact_results_user_id'):
            op.drop_index('ix_myimpact_results_user_id', table_name='myimpact_results')
        if index_exists('myimpact_results', 'ix_myimpact_results_assessment_id'):
            op.drop_index('ix_myimpact_results_assessment_id', table_name='myimpact_results')
        op.drop_table('myimpact_results')
    
    # 2. Drop columns from questions table (if exist)
    if index_exists('questions', 'ix_questions_instrument_type'):
        op.drop_index('ix_questions_instrument_type', table_name='questions')
    if column_exists('questions', 'section'):
        op.drop_column('questions', 'section')
    if column_exists('questions', 'instrument_type'):
        op.drop_column('questions', 'instrument_type')
    
    # 3. Drop columns from assessments table (if exist)
    if index_exists('assessments', 'ix_assessments_instrument_type'):
        op.drop_index('ix_assessments_instrument_type', table_name='assessments')
    if column_exists('assessments', 'instrument_type'):
        op.drop_column('assessments', 'instrument_type')
    
    # ### end Alembic commands ###
