<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Assessment Language Lines
    |--------------------------------------------------------------------------
    |
    | The following language lines are used with the assessment form and results
    | and other methods of data entry
    |
    */

    'abilities' => 'Habilidades',
    'almost-always' => 'Casi siempre',
    'almost-never' => 'Casi nunca',
    'answers' => 'respuestas',
    'apostle' => 'apóstol',
    'as-we-abide-with-jesus' => 'Mientras permanecemos en Jesús, Él crece en nosotros una pasión por las buenas obras que Él quiere que hagamos. Evaluaremos tres áreas de pasión: las personas, las causas y el estilo de influencia principal que utiliza para servir a esas personas y causas. Siga las instrucciones en cada categoría para discernir su pasión.',
    'assessments' => 'Evaluaciones',
    'assessment-started-on' => 'La evaluación comenzó el',
    'assessment-taken-on' => 'Evaluación asumida',
    'discern-your-spiritual-gifts' => 'Discernir sus Dones Espirituales.',
    'during-middle-age' => 'Durante la mediana edad',
    'during-my-childhood' => 'Durante mi niñez',
    'during-my-early-adulthood' => 'Durante la adultez temprana',
    'during-my-senior-years' => 'Durante mis años mayores',
    'during-my-youth' => 'Durante mi juventud',
    'causes' => 'causas',
    'completed' => 'terminado',
    'faith' => 'fe',
    'gifts' => 'regalos',
    'gifts-description' => 'Los dones espirituales y las habilidades naturales que Dios te ha dado.',
    'gps-assessment' => 'Evaluación GPS',
    'influencing-style' => 'Estilo influyente',
    'key-abilities' => 'habilidades clave',
    'knowledge' => 'conocimiento',
    'looking-back-into-your-story' => 'Mirando hacia atrás en tu historia',
    'now-about-spiritual-gifts-brothers' => '<span class="font-weight-medium">Ahora, amados hermanos, con respecto a la pregunta acerca de las capacidades especiales que el Espíritu nos da, no quiero que lo malentiendan.</span> 1 Corintios 12:1 (NTV)',
    'of' => 'de',
    'passions' => 'pasiones',
    'passions-description' => 'Las personas y las causas que le apasionan y la forma principal en que las atiende.',
    'people' => 'gente',
    'questions' => 'preguntas',
    'shepherd' => 'pastor',
    'score' => 'puntaje',
    'spiritual-influencing-styles' => 'Tus estilos de influencia espiritual (la puntuación más alta es primaria y la más baja es secundaria)',
    'statements' => 'declaraciones',
    'story' => 'historia',
    'story-description' => 'Mirando hacia atrás para ver cómo Dios ha estado escribiendo su historia y determinando su próximo paso.',
    'take-a-few-minutes-to-reflect-on-the-people' => 'Tómese unos minutos para reflexionar sobre las Personas y las Causas que seleccionó en la sección Pasión. Identifique cualquier experiencia de vida que pueda haberlo llevado a desarrollar estas pasiones en usted. Como recordatorio, a menudo son nuestras mayores luchas las que conducen a nuestro ministerio más significativo. Deje vacíos los períodos de tiempo que no correspondan.',
    'take-a-few-minutes-to-reflect-influencing-styles' => 'Tómese unos minutos para reflexionar sobre sus estilos de influencia primarios y secundarios. Identifique algunas experiencias de vida en las que reconozca que se utilizaron estos estilos. Después de identificar la experiencia, comparta si la experiencia fue un uso positivo de ese estilo de influencia o un uso menos útil. Incluya al menos un ejemplo positivo y uno inútil en sus respuestas.',
    'take-a-few-minutes-to-reflect-on-your-spiritual-gifts' => 'Tómese unos minutos para reflexionar sobre sus principales Dones Espirituales. A medida que lea las definiciones, identifique algunas ocasiones en las que estos dones estuvieron activos o se desarrollaron en el período de tiempo correspondiente. Deje vacíos los períodos de tiempo que no correspondan.',
    'take-a-few-minutes-to-reflect-on-your-abilities' => 'Tómese unos minutos para reflexionar sobre sus tres Habilidades principales. Identifique algunas ocasiones en las que se usaron o se desarrollaron estas habilidades en el período de tiempo correspondiente. Deje vacíos los períodos de tiempo que no correspondan.',
    'take-delight-in-the-lord' => '<span class="font-weight-medium">Deléitate en el Señor, y él te concederá los deseos de tu corazón.</span> Salmo 37:4 (NTV)',
    'teaching' => 'enseñando',
    'the-following-questions-will-help' => 'Las siguientes preguntas le ayudarán a identificar su:',
    'this-reflection-exercise-should-not-be-rushed' => 'Este ejercicio de reflexión no debe ser apresurado. Muchos se han beneficiado al preguntar a sus amigos y familiares si han visto estos dones y pasiones en el pasado y cuándo lo han hecho. Unos pocos ejemplos suelen ser suficientes para poner en marcha las ideas.',
    'to-discern-the-gifts-you-may-have' => 'Para discernir los dones que pueda tener, escriba el número que mejor represente su experiencia real después de cada declaración. (5-Casi siempre, 3-A veces, 1-Casi nunca)',
    'we-are-gods-masterpiece' => '<span class="font-weight-medium">Pues somos la obra maestra de Dios. Él nos creó de nuevo en Cristo Jesús, a fin de que hagamos las cosas buenas que preparó para nosotros tiempo atrás.</span> Efesios 2:10 (NTV)',
    'we-are-gods-workmanship' => '<span class="font-weight-medium">Pues somos la obra maestra de Dios. Él nos creó de nuevo en Cristo Jesús, a fin de que hagamos las cosas buenas que preparó para nosotros tiempo atrás.</span> Efesios 2:10 (NTV)',
    'we-will-prompt-you-to-think-back' => 'Le incitaremos a pensar en diferentes épocas de su vida... animándole a identificar aquellos momentos en los que los diferentes dones y pasiones estaban activos, incluso si no estaba consciente de ello. Todas las áreas de la vida, incluso aquellas que preferimos olvidar, brindan pistas significativas. Preste especial atención a su educación, recreación, trabajo, relaciones, logros y luchas.',
    'welcome-to-the-gps-assessment' => 'Bienvenido a la evaluación GPS',
    'when-we-abide-with-jesus' => 'Cuando permanecemos en Jesús, Su poder sobrenatural puede obrar a través de nosotros para edificar a otros en su búsqueda de Jesús. Este poder sobrenatural obra a través de los dones espirituales que Dios nos ha dado.',
    'wisdom' => 'sabiduría',
    'you-saw-me-before-i-was-born' => '<span class="font-weight-medium">Me viste antes de que naciera. Cada día de mi vida estaba registrado en tu libro. Cada
momento fue diseñado antes de que un solo día pasara.</span> Salmo 139:16 (NTV)',
    'your-current-gifts-passions-and-abilities' => 'Tus regalos, pasiones y habilidades actuales',
    'your-gps-assessment-results' => 'Los resultados de su evaluación de GPS',
    'your-influencing-styles' => 'Tus estilos influyentes',
    'your-life-is-a-story-that-god' => 'Tu vida es una historia que Dios ha estado escribiendo desde mucho antes de que nacieras. Cada una de las respuestas que ha proporcionado en esta evaluación de GPS ha sido informada por esa historia. La pregunta ahora es, "¿cuál es el próximo paso en mi historia?" La respuesta a esta pregunta se descubre parcialmente a través de dos prácticas; la reflexión personal y la retroalimentación de los compañeros. Esta sección de GPS lo guiará a través de una reflexión personal para prepararlo para solicitar comentarios de sus compañeros.',
    'your-spiritual-gifts' => 'Tus Dones Espirituales',

    // people list
    'infants-babies' => 'Infantes/Bebés',
    'toddlers' => 'Niños pequeños',
    'preschool-children' => 'Niños de preescolar',
    'elementary-children' => 'Niños de primaria',
    'jr-high-students' => 'Estudiantes de escuela intermedia',
    'high-school' => 'Escuela secundaria',
    'college-career' => 'Carrera universitaria',
    'women' => 'Mujeres',
    'men' => 'Hombres',
    'singles' => 'Solteros/Solteras',
    'single-parents' => 'Padres solteros/Madres solteras',
    'young-marrieds' => 'Jóvenes casados',
    'couples' => 'Parejas',
    'families' => 'Familias',
    'older-adults-60' => 'Adultos Mayores 60+',
    'other' => 'Otro',
    'other-2' => 'Otro 2',

    // causes list
    'families-marriage' => 'Familias/Matrimonio',
    'at-risk-children' => 'Niños en riesgo',
    'abuse-violence' => 'Abuso/Violencia',
    'financial-management' => 'Administración financiera',
    'divorce-recovery' => 'Recuperación del divorcio',
    'disabilities-and-or-support' => 'Discapacidades y/o Apoyo',
    'law-and-or-justice-system' => 'Sistema de Ley y/o Justicia',
    'sanctity-of-life' => 'Santidad de la vida',
    'homelessness' => 'Falta de vivienda',
    'recovery' => 'Rehabilitación',
    'working-with-prison-inmates-families' => 'Trabajo con reclusos/familias',
    'illness-and-or-injury' => 'Enfermedades y/o lesión',
    'sexuality-and-or-gender' => 'Problemas de sexualidad y/o género',
    'education' => 'Educación',
    'policy-and-or-politics' => 'Política y/o Leyes',
    'race' => 'Raza',
    'business-and-the-economy' => 'Negocios y Economía',
    'relief-efforts' => 'Los esfuerzos de alivio',
    'ethics' => 'Ética',
    'health-and-or-fitness' => 'Salud y/o Ejercicios',
    'science-and-or-technology' => 'Ciencia y/o Tecnología',
    'environment' => 'Ambiente',
    'international-and-global-affairs' => 'Asuntos Internacionales y Globales',
    'regional-state-or-federal-issues' => 'Problemas regionales, estatales o federales',
    'community-neighborhood-issues' => 'Problemas de la comunidad/vecindario',

    // abilities list
    'project-management' => 'Administración de proyectos',
    'information-technology' => 'Tecnologías de información',
    'communications' => 'Comunicaciones',
    'marketing' => 'Mercadeo',
    'community-relations' => 'Relaciones comunitarias',
    'social-media' => 'Medios de comunicación social',
    'web-development' => 'Desarrollo web',
    'graphic-arts' => 'Artes gráficas',
    'creative-arts' => 'Artes creativas',
    'music-vocal' => 'Música: Voz',
    'music-instrumental' => 'Música: Instrumental',
    'audio-visual' => 'Audiovisuales',
    'writing' => 'Escribir',
    'training' => 'Capacitación',
    'counseling' => 'Asesoramiento',
    'coaching' => 'Entrenamiento',
    'sports' => 'Deportes',
    'plumbing' => 'Plomería',
    'cooking' => 'Cocina',
    'mechanical' => 'Mecánico',
    'electrical' => 'Eléctricista',
    'landscaping-gardening' => 'Paisajismo/Jardinería',
    'carpentry-construction' => 'Carpintería/Construcción',
];
