<?php

return [
    'complete-the-form-below-to-claim-your-registration' => 'Complete el siguiente formulario para reclamar su registro para el <strong>:name</strong> comunidad.',
    'content-forbidden' => 'No tienes permiso para ver este contenido..',
    'create-account' => 'Crear una cuenta',
    'create-your-account' => 'Crea tu cuenta',
    'dont-just-read-the-book' => 'No se limite a leer el libro... ¡Cree una cultura!',
    'discover-your-gifts' => 'Descubre tus REGALOS. Entiende tus PASIONES. Comprende la HISTORIA que Dios está escribiendo a través de tu vida. ¡Empieza ahora mismo!',
    'dont-have-account' => '¿No tienes una cuenta?',
    'enter-your-information-create' => 'Ingrese su información para crear una cuenta gratuita.',
    'failed' => 'Estas credenciales no coinciden con nuestros registros.',
    'forgot-password' => 'Has olvidado tu contraseña',
    'find-your-place' => 'Listo para encontrar tu lugar',
    'free-assessment-registration' => 'Registro de evaluación gratuito',
    'gifts-passion-story' => 'Regalos Historia de Pasión',
    'login' => 'Acceso',
    'not-ready-to-take-assessment' => 'Si no está listo para realizar la evaluación, <a href=":url">vuelva al sitio web Gift Passion Story.</a>',
    'password' => 'La contraseña es incorrecta.',
    'profile' => 'Perfil',
    'questions-email-us' => '¿Preguntas? Envíanos un email a',
    'reset-password' => 'Restablecer la contraseña',
    'select-package' => 'Seleccionar paquete',
    'sign-up' => 'Inscribirse',
    'throttle' => 'Demasiados intentos de acceso. Por favor intente nuevamente en :seconds segundos.',
    'update-password' => 'Actualiza contraseña',
    'welcome-back' => 'Bienvenido de nuevo',
    'welcome-to-the-dm-family' => '¡Bienvenido a la familia Disciples Made! Empecemos.',
    'you-are-now-logged-in' => 'Ahora está conectado',
    'you-can-do-it' => 'Puedes hacerlo. Nuestros Paquetes de Implementación de la Iglesia pueden ayudar.',
    'you-must-login' => 'Debes iniciar sesión para ver este contenido.',
];
