<?php

return [
    'a-new-gift-passion-story-experience' => 'Una nueva experiencia GPS (Regalos, Pasiones, Historia)',
    'a-new-gift-passion-story-experience-action-required' => 'Una nueva Experiencia GPS (Regalos, Pasiones, Historia): Acción Requerida',
    'blessings-to-you-as-you-pursue-the-masterpiece' => '¡Bendiciones para ti mientras persigues la misión extraordinaria que Jesús tiene para ti!',
    'complete-sign-up' => 'Complete el registro',
    'congratulations-on-creating-your-gps-account' => '¡Felicitaciones por crear su cuenta de GPS!',
    'congratulations-on-creating-your-gps-account-ready-to-learn' => '¡Felicitaciones por crear su cuenta de GPS! Ahora está listo para conocer sus dones, su pasión y su historia a través de su evaluación GPS. Nuestra evaluación de GPS ha demostrado ayudar a muchas personas a dar el próximo paso significativo en su llamado personal. Puede realizar la evaluación tantas veces como desee.',
    'congratulations-on-your-purchase' => 'Felicidades por tu compra',
    'congratulations-on-your-purchase-we-are-excited-to-have-you' => '¡Felicitaciones por su compra de GPS! Estamos emocionados de tenerte a ti y a tu iglesia a bordo con nosotros mientras nos esforzamos por movilizar a cada seguidor de Jesús a su llamado personal. Puede comenzar a revisar sus materiales de inmediato.',
    'date' => 'Fecha',
    'for-best-results-we-encourage-your' => 'Para obtener los mejores resultados, le alentamos a que realice la evaluación mientras lee la guía complementaria; Encuentra tu lugar. Puede obtener más información sobre el libro y comprarlo en su tienda favorita.',
    'hi-name' => 'Hola :name',
    'hi-its-brian-from-gifts-passion-story' => 'Hola :name, soy Brian de GPS (Regalos, Pasión, Historia)',
    'if-you-are-registered-with-a-church' => 'Si está registrado en una iglesia, tenga en cuenta que los administradores de GPS de esa iglesia podrán ver y realizar una consulta de búsqueda de los resultados de su evaluación. Si tiene alguna pregunta o inquietud, comuníquese con ellos para obtener más información.',
    'if-you-have-questions-please-email-us' => 'Si tiene preguntas, envíenos un correo electrónico a <a href="mailto:info@disciplesmade.com">info@disciplesmade.com</a> o llame al <a href="tel:913-343-0321">913-343-0321</a>.',
    'if-you-purchased-a-gold-or-platinum-kit' => 'Si compró un kit Oro o Platino, tiene acceso a los datos de los miembros de su iglesia durante 365 días, lo cual puede renovar anualmente por $99 al año. También se incluye en su paquete una llamada de entrenamiento individual de 30 minutos. Un entrenador se comunicará con usted pronto para programar su llamada, o puede solicitarla enviándonos un correo electrónico a <a href="mailto:info@disciplesmade.com">info@disciplesmade.com</a>',
    'login' => 'Login',
    'paid-to-gps' => '<i>Pagado a:</i><br>GPS (Regalos, Pasión, Historia)',
    'please-keep-this-receipt-for-your-records' => 'Guarde este recibo para sus registros. ¡Pronto se enviará correspondencia adicional para ayudarle a comenzar!',
    'please-note-that-this-does-not-change' => 'Tenga en cuenta que esto no cambia la funcionalidad que está disponible para usted; ¡todavía puede realizar tantas evaluaciones como desee! Lo que esto significa es que los administradores de la iglesia podrán ver los resultados de su evaluación; estarán al tanto de sus dones, pasiones e historias identificadas en su evaluación más reciente. Si tiene alguna pregunta o inquietud, comuníquese con ellos para obtener más información.',
    'purchase-book' => 'Compre el Libro',
    'sincerely' => 'Atentamente,<br><br><i>Brian Phipps</i><br>Presidente: Disciples Made, Inc.',
    'thank-you-for-your-purchase' => 'Gracias por su compra',
    'thank-you-so-much-for-being-a-valued-gps-user' => 'Muchas gracias por ser un valioso usuario de la Experiencia GPS. Hemos lanzado una nueva experiencia GPS. Para acceder a la nueva experiencia, haga clic a continuación.',
    'thank-you-for-your-purchase-of-your-gps-kit' => '¡Gracias por comprar su kit de implementación de GPS! Estamos emocionados de tenerte a ti y a tu iglesia a bordo.',
    'to-access-previous-gps-assessments-and-take-new-assessments' => 'Para acceder a evaluaciones GPS anteriores y tomar nuevas evaluaciones, debe restablecer su contraseña haciendo clic en "Olvidé mi contraseña" e ingresando la dirección de correo electrónico asociada con su cuenta. ¡Después de restablecer su contraseña, puede disfrutar de todas las funciones nuevas y mejoradas de la aplicación! Si tiene alguna pregunta, por favor póngase en contacto conmigo en <a href="mailto:brian@disciplesmade.com">brian@disciplesmade.com</a>.',
    'we-are-glad-to-have-you-onboard' => '¡Nos complace tenerte a bordo!',
    'we-have-added-you-as-a-church-administrator' => 'Te hemos agregado como administrador de la iglesia <strong>:organization</strong>. Haga clic en el enlace a continuación para crear su identificación de usuario.',
    'we-look-forward-to-serving-you' => '¡Esperamos poder servirle a usted y a sus miembros!',
    'we-look-forward-to-our-future-partnership' => '¡Estamos emocionados por nuestra futura asociación!',
    'welcome-to-the-new-gps-experience' => 'Bienvenido a la nueva experiencia GPS (Regalos, Pasión, Historia)',
    'youve-been-assigned-to-a-church' => 'Te han asignado a una iglesia',
    'youve-been-recently-assigned-to-the-church' => 'Ha sido asignado recientemente a la iglesia <strong>:name</strong>.',
];
